version: '3.7'

services:
  proxy:
    env_file: .env
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    
  db:
    image: postgres:11
    env_file: .env      
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  db_data:
  redis_data:
    
networks:
  default:
    external:
      name: property-app-net
