[tool.poetry]
name = "property_app"
version = "0.1.0"
description = ""
authors = ["Anthony <anthony@mcclosky.dev>"]

packages = [
    { include = "property_app", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.3.13"
flask-migrate = "^2.5.2"
flask = "^1.1.1"
flask-sqlalchemy = "^2.4.1"
flask-debugtoolbar = "^0.10.1"
sqlalchemy-utils = {version = "^0.36.1", extras = ["arrow"]}
structlog = "^20.1.0"
python-dotenv = "^0.10.5"
gunicorn = {version = "^20.0.4", extras = ["gthread"]}
pandas = "^1.0.0"
Flask-Static-Digest = "^0.1.3"

[tool.poetry.dev-dependencies]
flask-shell-ipython = "^0.4.1"
pytest = "^5.3.5"
invoke = "^1.4.1"
fabric = "^2.5.0"
patchwork = "^1.0.1"
tox = "^3.14.3"
awscli = "^1.17.9"
black = "^19.10b0"

[tool.black]
line-length = 120
target-version = ["py37"]

[tool.isort]
atomic = true
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

known_first_party = ["property_app"]
known_third_party = [
     "alembic",
     "arrow",
     "boto3",
     "click",
     "fabric",
     "flask",
     "flask_redis",
     "flask_sqlalchemy",
     "furl",
     "invoke",
     "lxml",
     "patchwork",
     "requests",
     "setuptools",
     "sqlalchemy",
     "sqlalchemy_utils",
     "structlog"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

