version: '3.6'

x-logging:
  &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "5m"
      max-file: "10"

x-flask:
  &default-flask
  restart: always
  image: "${APP_REPO}:prod"
  env_file:
    - .env
  depends_on:
    - redis

services:
  proxy:
    <<: *default-logging
    restart: always
    image: "${PROXY_REPO}:prod"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
  app:
    <<: *default-flask
    <<: *default-logging
    ports:
      - "5000"
    command: ["/opt/venv/bin/gunicorn", "-c", "gunicorn.conf.py", "property_app:create_app()"]
  worker:
    <<: *default-flask
    <<: *default-logging
    command: ["/opt/venv/bin/flask", "rq", "worker"]
  scheduler:
    <<: *default-flask
    <<: *default-logging
    command: ["/opt/venv/bin/flask", "rq", "scheduler"]
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  redis_data:
